on: [ push ]


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires

      # 上传项目

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: hanser
          directory: ./hanser
          branch: main
          # Optional: Enable this if you want to have GitHub Deployments triggered
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      # 清除域名代理缓存

      - name: Clear Cloudflare cache
        uses: Cyb3r-Jak3/action-cloudflare-cache@v1.1.0
        with:
          # Zone is required by both methods
          zone: ${{ secrets.CLOUDFLARE_ZONE }}

          # Using API Token
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}